config/routes.rb
Altereot::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

=begin
  match 'article/:id/criterion/:criterion_id/delete' => 'articles#criterion_delete', :as => :article_criterion_delete
  
  match 'date_sort/:date_type(/:order_by)' => 'articles#date_sort', :as => :date_sort
  match 'criterion_choose/:criterion_id' => 'articles#criterion_choose', :as => :criterion_choose
  match 'reset_filter_selection' => 'articles#reset_filter_selection', :as => :reset_filter_selection
  match 'select_filter/:filter_id(.:format)' => 'articles#select_filter', :as => :select_filter
  match 'filter_sort/:index/:order_by' => 'articles#filter_sort', :as => :filter_sort
  match 'delete_filter_selection/:index' => 'articles#delete_filter_selection', :as => :delete_filter_selection ###???
  
  match 'add_criterion/:num' => 'articles#add_criterion', :as => :add_criterion
  
  match 'comment_article/new.js/:parent_article' => 'comments#new', :as => :new_comment_article
  match 'comment_comment/new.js/:parent_comment' => 'comments#new', :as => :new_comment_comment
  resources :comments
  
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :login
    get 'logout', :to => 'devise/sessions#destroy', :as => :logout
    get 'register', :to => 'devise/registrations#new', :as => :register
    
  end
  
  devise_for :users#, :controllers => { :sessions => "users/sessions" }

  mount Ckeditor::Engine => '/ckeditor'

  resources :articles do
    collection do
      get 'search'
      post 'update_search'
    end
  end
  
  match 'criterions/:filter_id/autocomplete' => 'criterions#autocomplete'
  
=end
  #DMP-----------------------------------
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :dmp_admins
  match 'dmp' => 'dmp#index', :as => :dmp
  match 'dmp/show/:id' => 'dmp#show', :as => :dmp_show
  match 'dmp/show_vkusers/:id' => 'dmp#show_vkusers', :as => :dmp_show_vkusers
  match 'dmp/new' => 'dmp#new', :as => :dmp_new
  match 'dmp/edit/:id' => 'dmp#edit', :as => :dmp_edit
  match 'dmp/create' => 'dmp#create', :as => :dmp_create
  match 'dmp/update/:id' => 'dmp#update', :as => :dmp_update
  match 'dmp/destroy/:id' => 'dmp#destroy', :as => :dmp_destroy
  
  # match 'country_ok_ajax' => 'dmp#country_ok_ajax', :as => :country_ok_ajax
  #   match 'city_ok_ajax' => 'dmp#city_ok_ajax', :as => :city_ok_ajax
  #   match 'school_ok_ajax' => 'dmp#school_ok_ajax', :as => :school_ok_ajax
  #   match 'university_ok_ajax' => 'dmp#university_ok_ajax', :as => :university_ok_ajax
  match 'vkuser_sent' => 'dmp#vkuser_sent'
  
  match 'country_autocomplete' => 'dmp#country_autocomplete', :as => :country_autocomplete
  match 'city_autocomplete(/:country)' => 'dmp#city_autocomplete', :as => :city_autocomplete
  match 'school_autocomplete(/:city)' => 'dmp#school_autocomplete', :as => :school_autocomplete
  match 'university_autocomplete(/:country/:city)' => 'dmp#university_autocomplete', :as => :university_autocomplete
  #DMP===================================


  root :to => 'dmp#index'

end

app/views/articles/_articles.html.erb
<% @articles.each do |article| %>
  <h3 class="inline"><%= link_to article.name, article %></h3>
  <font size="1">
    <%= link_to 'Edit', edit_article_path(article), :style => "font-size: 8px" %>
    <%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete, :style => "font-size: 8px" %>
  </font>
  <br>
  <%#= article.rating_id %>
  <!-- <div class="article_criterions">
      <% article.criterions.each do |criterion| %>
      <div id="criterion<%= criterion.id %>" class="article_criterion" style="background: #<%= (criterion.filter.name.hash % 0xffffff).to_s(16) %>">
        <%= criterion.name %>
      </div>
      <% end %>
      <font size="1"> <%= article.created_at.strftime("%d.%m %H:%M:%S") %> </font>
    </div> -->
  
<% end %>

app/views/articles/_criterions.html.erb
<%- @selected_filters.each_with_index do |filter_order_by, i| -%><%- filter, order_by = filter_order_by[0], filter_order_by[1] -%><div id="criterions_filter_<%= filter.id %>" class="criterions_filter">
    <ul>
      <% filter.criterions.each do |criterion| %>
        <% if session[:criterion_ids] and session[:criterion_ids].include?(criterion.id)  %>
          <li class="selected"><%= link_to criterion.name, criterion_choose_path(criterion.id) %></li>
        <% else %>
          <li><%= link_to criterion.name, criterion_choose_path(criterion.id), :title => criterion.name %></li>
        <% end %>
      <% end %>
    </ul>
    <hr>
    <%= link_to "ok", '/' %>
  </div><%- end -%>

app/views/articles/_filters.html.erb
<hr>
<div id="filters">
  Фильтры:
  <% @filters.each do |filter| %>
  <div id="filter<%= filter.id %>" class="filter">
    <%= link_to filter.name, select_filter_path(filter), :class => "filter_link" %>
  </div>
  <% end %>
</div>
<hr>
Сортировка по дате создания: <br>
<%= link_to image_tag("arrow_up.png", height: "20px"), date_sort_path('created_at', 'asc') %>
<%= link_to image_tag("arrow_down.png", height: "20px"), date_sort_path('created_at', 'desc') %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id  = "error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class = "field">
    <%= f.label :content %><br />
    <%#      = f.text_area :content %>
    <%= f.cktext_area :content, :toolbar => 'Full', :width => 800, :height => 400 %>
  </div>
  <a href="" id="add_criterion_link">add criterions</a>
  <div id="add_criterions">
  </div>
  <div class = "actions">
    <%= f.submit "Создать"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= content_for :leftside do %>
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
<% end %>

app/views/articles/index.html.erb
<%= content_for :leftside do %>
  <div id="all_filters_criterions" class="criterions_filter">
    <% @all_filters_criterions.each do |filter, criterions| %>
      <p style="font-weight: bold"><%= filter %></p>
      <ul>
        <% criterions.each do |criterion| %>
          <li style="margin-left: 5px; margin-top: 5px"><%= criterion[1] %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <%= render 'criterions' %>
  <div id="articles" style="width: <%= 850 -(@selected_filters.size + 1) * 114%>px">
    <%= render 'articles' %>
  </div>
  
<% end %>


<%= content_for :selected_filters do%>
  <div id="none" class="filter selected">
    Выбраные:
  </div>
  <% @selected_filters.each_with_index do |filter_order_by, i| %>
      <% filter = filter_order_by[0] %>

      <div id="filter<%= filter.id %>" class="filter selected">
        <%= link_to filter.name, delete_filter_selection_path(i) %>      
      </div>
    <% end %>
    <% if session[:filter_sorting] %>
      <% if session[:filter_sorting][1] == "desc" %>
        <%= link_to image_tag("arrow_up.png", :height => "10px"), filter_sort_path(:index => 0, :order_by => :asc) %>
      <% else %>
        <%= link_to image_tag("arrow_down.png", :height => "10px"), filter_sort_path(:index => 0, :order_by => :desc) %>
      <% end %>
    <% end %>
    <div id="reset_filter_selection">
      <%= link_to 'clear', reset_filter_selection_path unless @selected_filters.empty? %>
    </div>
<% end %>

app/views/articles/index.html.haml
= content_for :leftside do
  #left_container{style: "width: #{152 + @selected_filters.size*102}px;"}<
    .criterions_filter{style: "width: 152px;"}
      .filter.selected{style: "width: 152px;"}
        Выбранные:
      %ul{id: "all_filters_criterions", type: 'none'}
  / #articles
  /   = render 'articles'

app/views/articles/new.html.erb
<% content_for :head do %>
<% end %>
<%= content_for :leftside do %>
<h1>Новая статья</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
<% end %>

app/views/articles/new.html.haml
=content_for :head do
  <script>
      
  </script>
= content_for :leftside do
  %h1 Новая статья

  = render 'form'

  = link_to 'Back', articles_path

app/views/articles/search.html.haml
= content_for :head do
  - @selected_filters.each do |filter, order_by| 
    :javascript
      $(document).ready(function(){
        $('#criterions_filter_#{filter.id}_hide').click(function(){
          $("#criterions_filter_#{filter.id}").toggle();
          return false;
        });
      })

= content_for :leftside do
  #left_container{style: "width: #{152 + @selected_filters.size*102}px;"}
    #all_filters_criterions.criterions_filter
      #all_selected_filters.filter.selected 
        Выбранные:
      - @all_filters_criterions.each do |filter, criterions|
        %div{style: "font-weight: bold"}= filter
        %ul
          - criterions.each do |criterion| 
            %li{style: "margin-left: 5px; margin-top: 5px"}= criterion[1]
          
    - @selected_filters.each_with_index do |filter_order_by, i| 
      - filter, order_by = filter_order_by[0], filter_order_by[1]
      .criterions_filter{id: "criterions_filter_#{filter.id}"}>
        .filter.selected{id: "filter#{filter.id}"}
          = link_to filter.name, delete_filter_selection_path(i)
        %ul
          - filter.criterions.each do |criterion| 
            - if session[:criterion_ids] and session[:criterion_ids].include?(criterion.id) 
              %li{class: "selected"}= link_to criterion.name, criterion_choose_path(criterion.id)
            - else
              %li= link_to criterion.name, criterion_choose_path(criterion.id), :title => criterion.name
        %hr
        = link_to "ok", '', :id => "criterions_filter_#{filter.id}_hide"
        / <div id="reset_filter_selection">
        /           <%= link_to 'clear', reset_filter_selection_path unless @selected_filters.empty? %>
        /         </div>

app/views/articles/show.html.erb
<%= content_for :leftside do %>
<div id="articles" class='inline'>
<p id="notice"><%= notice %></p>

  <h2><%= @article.name %></h2>

<div class="content">
  <%= raw @article.content %>
  <div class="comment_button"><%= link_to 'comment it', new_comment_article_path(@article.id), :remote => true %></div>
</div>

<p>
  <b>Rating:</b>
  <%= @article.rating_id %>
</p>

<div class="criterions" style="background: #ddd">
  <% @article.criterions.each do |criterion| %>
    <div id="criterion<%= criterion.id %>" class="criterion">
      <%= criterion.name %>
      <%= link_to "x", article_criterion_delete_path(@article, criterion) %>
    </div>
  <% end %>
</div>

<font size="4">Комментарии:</font>

<div id="comments" class="comments">
  <%= render :partial => "comments/comment", :collection => @article.comments %>
</div>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
</div>
<div id="rightside" class='inline'>
  <div id="user_nav" class="inline">
    <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", logout_path %>
    <% else %>
    <%= link_to "Register", register_path %> or
    <%= link_to "log in", login_path %>
    <% end %>
  </div>
  <div id="new_article" class="inline">
    <%= link_to 'New Article', new_article_path %>
  </div>
</div>
<% end %>