config/routes.rb
Altereot::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

=begin
  match 'article/:id/criterion/:criterion_id/delete' => 'articles#criterion_delete', :as => :article_criterion_delete
  
  match 'date_sort/:date_type(/:order_by)' => 'articles#date_sort', :as => :date_sort
  match 'criterion_choose/:criterion_id' => 'articles#criterion_choose', :as => :criterion_choose
  match 'reset_filter_selection' => 'articles#reset_filter_selection', :as => :reset_filter_selection
  match 'select_filter/:filter_id(.:format)' => 'articles#select_filter', :as => :select_filter
  match 'filter_sort/:index/:order_by' => 'articles#filter_sort', :as => :filter_sort
  match 'delete_filter_selection/:index' => 'articles#delete_filter_selection', :as => :delete_filter_selection ###???
  
  match 'add_criterion/:num' => 'articles#add_criterion', :as => :add_criterion
  
  match 'comment_article/new.js/:parent_article' => 'comments#new', :as => :new_comment_article
  match 'comment_comment/new.js/:parent_comment' => 'comments#new', :as => :new_comment_comment
  resources :comments
  
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :login
    get 'logout', :to => 'devise/sessions#destroy', :as => :logout
    get 'register', :to => 'devise/registrations#new', :as => :register
    
  end
  
  devise_for :users#, :controllers => { :sessions => "users/sessions" }

  mount Ckeditor::Engine => '/ckeditor'

  resources :articles do
    collection do
      get 'search'
      post 'update_search'
    end
  end
  
  match 'criterions/:filter_id/autocomplete' => 'criterions#autocomplete'
  
=end
  #DMP-----------------------------------
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :dmp_admins
  match 'dmp' => 'dmp#index', :as => :dmp
  match 'dmp/show/:id' => 'dmp#show', :as => :dmp_show
  match 'dmp/show_vkusers/:id' => 'dmp#show_vkusers', :as => :dmp_show_vkusers
  match 'dmp/new' => 'dmp#new', :as => :dmp_new
  match 'dmp/edit/:id' => 'dmp#edit', :as => :dmp_edit
  match 'dmp/create' => 'dmp#create', :as => :dmp_create
  match 'dmp/update/:id' => 'dmp#update', :as => :dmp_update
  match 'dmp/destroy/:id' => 'dmp#destroy', :as => :dmp_destroy
  
  # match 'country_ok_ajax' => 'dmp#country_ok_ajax', :as => :country_ok_ajax
  #   match 'city_ok_ajax' => 'dmp#city_ok_ajax', :as => :city_ok_ajax
  #   match 'school_ok_ajax' => 'dmp#school_ok_ajax', :as => :school_ok_ajax
  #   match 'university_ok_ajax' => 'dmp#university_ok_ajax', :as => :university_ok_ajax
  match 'vkuser_sent' => 'dmp#vkuser_sent'
  
  match 'country_autocomplete' => 'dmp#country_autocomplete', :as => :country_autocomplete
  match 'city_autocomplete(/:country)' => 'dmp#city_autocomplete', :as => :city_autocomplete
  match 'school_autocomplete(/:city)' => 'dmp#school_autocomplete', :as => :school_autocomplete
  match 'university_autocomplete(/:country/:city)' => 'dmp#university_autocomplete', :as => :university_autocomplete
  #DMP===================================


  root :to => 'dmp#index'

end

app/controllers/dmp_controller.rb
#encoding: utf-8
class DmpController < ApplicationController
  layout false
  helper_method :is_user?
  helper_method :is_admin?
  before_filter :can_user?
  before_filter :can_admin?, :only => [:new, :create, :edit, :update, :destroy]
  def index
    @dmp_requests = DmpRequest.all
        # while @vkusers.size < 20
    #       @vkusers = Vkuser.get_vkusers({:city => 10, :country => 1, :name => 1, :section => "people"}, offset) #:q => "Ivan",
    #       offset += 20
    #     end
  end
  
  def country_autocomplete
    response = Vkuser.get_countries 
    render response
  end
  
  def city_autocomplete
    country_id = "1"
    country_id = Vkuser.get_country_id params[:country] if params[:country]
    response = Vkuser.get_cities country_id, params[:term]
    render :json => response
  end
  
  def school_autocomplete
    city_id = "1"
    city_id = Vkuser.get_city_id params[:city] if params[:city]
    response = Vkuser.get_schools city_id, params[:term]
    render :json => response
  end
  
  def university_autocomplete
    country_id = "1"
    country_id = Vkuser.get_country_id params[:country] if params[:country]
    city_id = "1"
    city_id = Vkuser.get_city_id params[:city] if params[:city]
    response = Vkuser.get_universities country_id, city_id, params[:term]
    render :json => response
  end
  
  # def country_ok_ajax
  #    if params[:country]
  #      @country = params[:country]
  #      country_id = Vkuser.get_country_id params[:country]
  #      if country_id 
  #        session[:dmp_country] = country_id
  #        render 'country_ok'
  #      else
  #        render 'error_country_ok'
  #      end
  #    else
  #      render 'error_country_ok'
  #    end
  #  end
  #  
  #  def city_ok_ajax
  #    
  #  end
  #  
  #  def school_ok_ajax
  #    
  #  end
  #  
  #  def university_ok_ajax
  #    
  #  end
  #  
  def show
    @dmp_request = DmpRequest.find(params[:id])
    @vkusers = current_dmp_admin.vkusers(@dmp_request).compact
    @content = ""
  end
  
  def show_vkusers
    @dmp_request = DmpRequest.find(params[:id])
    @vkusers = current_dmp_admin.vkusers(@dmp_request).compact
    index = 0
    vksize_buf = -1
    offset = @dmp_request.offset
    @error = nil
    @content = Vkuser.get_vkusers(@dmp_request, offset, current_dmp_admin)
    while @vkusers.size < 20 and (index += 1) <= 100
      ans, status = Vkuser.get_vkusers(@dmp_request, offset, current_dmp_admin) 
      if status == 1
        @error = "Vk DOM changed"
        break 
      elsif status == 2
        break
      end
      @vkusers += ans
      if status == 0
        @dmp_request.offset += 20 unless @dmp_request.online == 1 or (@dmp_request.query.match(/c\[online\]=(\d)/) and @dmp_request.query.match(/c\[online\]=(\d)/)[1] == "1")
        @dmp_request.save
      end
      offset += 20 unless @dmp_request.online == 1 or @dmp_request.query.match(/c\[online\]=(\d)/)[1] == "1"
    end
    @vkusers.compact!
    render 'show'
  end
    
  def vkuser_sent
    vkuser = Vkuser.find(params[:vkid])
    vkuser.sent = true
    vkuser.save
    vkuser.dmp_admin_dmp_request_vkuser.destroy
    render :nothing => true
  end
  
  def new
    @countries = Vkuser.get_countries
    @dmp_request = DmpRequest.new
  end
  
  def create
    request_params = get_request_from_params params[:dmp_request]
    @dmp_request = DmpRequest.new(request_params)
    @dmp_request.start_offset = @dmp_request.offset
    if @dmp_request.valid?
      @dmp_request.save
      redirect_to '/dmp', :notice => "created"
    else
      redirect_to '/dmp/new', :notice => "error: #{@dmp_request.errors.full_messages}"
    end
  end
  
  def edit
    @countries = Vkuser.get_countries
    @dmp_request = DmpRequest.find(params[:id])
    @dmp_request.nilify!
  end  
  
  def update
    @dmp_request = DmpRequest.find(params[:id])
    request_params = get_request_from_params params[:dmp_request]
    puts "update:"
    p request_params
    @dmp_request.start_offset = request_params[:offset]
    request_params.delete(:offset)
    if @dmp_request.update_attributes(request_params)
      redirect_to '/dmp', :notice => "updated"
    else
      redirect_to "/dmp/edit/#{params[:id]}", :notice => "error: #{@dmp_request.errors.full_messages}"
    end
  end
  
  def destroy
    dmp_request = DmpRequest.find(params[:id])
    dmp_request.destroy
    redirect_to '/dmp'
  end
  protected
  def get_request_from_params params
    country_id, city_id, university_id, school_id = nil, nil, nil, nil
    unless params[:country].blank?
      country_id = Vkuser.get_country_id params[:country].gsub(/<.*?>/,'').strip
      params[:country] = country_id
    end
    unless params[:city].blank?
      country_id = 1 unless country_id
      city_id = Vkuser.get_city_id country_id, params[:city].gsub(/<.*?>/,'').strip
      params[:city] = city_id
    end
    unless params[:university].blank?
      country_id = 1 unless country_id
      city_id = 1 unless city_id
      university_id = Vkuser.get_university_id country_id, city_id, params[:university].gsub(/<.*?>/,'').strip
      params[:university] = university_id
    end
    unless params[:school].blank?
      city_id = 1 unless city_id
      school_id = Vkuser.get_school_id city_id, params[:school].gsub(/<.*?>/,'').strip
      params[:school] = school_id
    end
    return params
  end
  def is_user?
    current_dmp_admin and current_dmp_admin.role >= 1
  end
  def is_admin?
    current_dmp_admin and current_dmp_admin.role >= 2
  end
  def can_user?
    unless is_user?
      redirect_to new_dmp_admin_session_path, notice: "U are not allowed to do this"
    end
  end
  def can_admin?
    unless is_admin?
      redirect_to new_dmp_admin_session_path, notice: "U are not allowed to do this"
    end
  end
end

app/helpers/dmp_helper.rb
module DmpHelper
end

app/views/dmp/_form.html.erb
<%= f.submit 'Создать задание' %><br>
Автозаполнение для города, универа и школы пока работает только для России и Москвы.
<table>
  <tr>
    <td> Название: </td>
    <td> <%= f.text_field :name %> </td>
  </tr>
  <tr>
    <td> Сообщение: </td>
    <td> <%= f.text_area :content, :input_html => { :value => "Текст для отправки пользователям."}, :toolbar => 'Basic', :width => 600 %></td>
  </tr>
  <tr>
    <td>Поисковый URL</td>
    <td>
      <%= f.text_field :query %>
    </td>
  </tr>
  <tr>
    <td>Отступ от начала списка: </td>
    <td><%= f.text_field :offset, :size => 5 %> </td>
  </tr>
</table>

app/views/dmp/country_ok.js.erb
$('#td_autocomplete_country').html('
<div class="ok_ajax"><%= @country %></div>
')

app/views/dmp/edit.html.erb
<html>
<head>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body style="padding: 20px">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}", :class => "#{name}" %>
  <% end %>
  <h2>Отредактировать запрос:</h2>
  <%= form_for @dmp_request, :url => dmp_update_path(@dmp_request) do |f| %>
    <%= render :partial => "form", :locals => {:f => f} %>
  <% end %>
</body>
</html>

app/views/dmp/index.html.erb
<html>
<head>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body style="padding: 20px">
  <%= link_to 'login', new_dmp_admin_session_path %> | <%= link_to 'logout', destroy_dmp_admin_session_path, method: :delete if dmp_admin_signed_in? %><br>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}", :class => "#{name}" %>
  <% end %>
  <hr>
  <% if is_user? %>
    <% @dmp_requests.each do |dmp_request| %>
      <%= link_to dmp_request.name, dmp_show_path(dmp_request.id) %> 
      <font size="1">
        <%= link_to "Edit", dmp_edit_path(dmp_request.id) if is_admin? %> 
        <%= link_to "Destroy", dmp_destroy_path(dmp_request.id) if is_admin? %>
      </font><br>
    <% end %>
  <% end %>
  <hr>
  <% if is_admin? %>
    <%= link_to "Новый запрос", dmp_new_path %>
  <% end %>
</body>
</html>

app/views/dmp/new.html.erb
<html>
<head>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body style="padding: 20px">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}", :class => "#{name}" %>
  <% end %>
  <h2>Создать новый запрос:</h2>
  <%= form_for @dmp_request, :url => dmp_create_path do |f| %>
    <%= render :partial => "form", :locals => {:f => f} %>
  <% end %>
</body>
</html>

app/views/dmp/show.html.erb
<html>
<head>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%#= javascript_include_tag "ZeroClipboard" %>
  <!--<script type="text/javascript">
    ZeroClipboard.setMoviePath( 'http://localhost:3000/assets/ZeroClipboard.swf' );
    var clip = new ZeroClipboard.Client();
  </script>
  -->
  <%= csrf_meta_tag %>
</head>
<body style="padding: 20px">
  <div id="request">
    <h1><%= @dmp_request.name %></h1>
    <div id="request_content">
      Содержание сообщения: <br>
      <p class="dmp_content" id='dmp_content' style="display: none;"><%= @dmp_request.content %></p>
      <div class="dmp_view_content"><%= raw RedCloth.new(@dmp_request.content).to_html %></div>
      <!--
      <div id="d_clip_container" style="position:relative;">
        <div id="d_clip_button">Скопировать</div>
      </div>
      
      <script type="text/javascript" >
        clip.setText('<%= escape_javascript @dmp_request.content %>');
        clip.glue( 'd_clip_button', 'd_clip_container' );
      </script>
      -->
      <hr>
      <% if is_admin? %>
        Параметры: <br>
        <br>
        <% @dmp_request.vk_attrs.delete_if{|k, v| v.blank?}.each do |k, v| %>
          <p><%= k %>: <%= v %></p>
        <% end %>
        <a href="http://vk.com/search?<%= @dmp_request.query %>"> check url </a>
      <% end %>
      <span id="check_url"></span> 
    </div>
    <br>
    <%= link_to "Edit", dmp_edit_path(@dmp_request.id) if is_admin? %> 
    <%= link_to "Destroy", dmp_destroy_path(@dmp_request.id) if is_admin? %>
  </div>
  <%= link_to "Получить список отправки", dmp_show_vkusers_path(@dmp_request.id) %>
  <div id="vkusers">
    <% @vkusers.each do |vkuser| %>
      <%= link_to "http://vk.com/write#{vkuser.vkid}", "#", :target => "_blank", id: vkuser.vkid.to_s %><br>
      <script>                                                                                       
        $('#<%= vkuser.vkid %>').click(function(){                                                   
          $.ajax({                                                                                   
            type: 'POST',                                                                            
            url: '/vkuser_sent',                                                                     
            data: {vkid: <%= vkuser.vkid %>}                                                         
          })
          $(this).attr('class', 'dmp_sent');
          open_in_new_tab("http://vk.com/write<%=vkuser.vkid%>");
          return false;
        })                                                                                           
      </script>
    <% end %>
    
  </div>
</body>
</html>

app/views/dmp/show_vkusers.js.erb
<% if @error %>
  $('#vkusers').append("<hr>");
  $('#vkusers').append('<div class="notice"><%= @error %></div>');
<% else %>
  $('#vkusers').append("<hr>");
  $('#vkusers').append("<%= @content %>");
<% end %>

app/views/dmp/show_vkusers_buf.js.erb
<% if @error %>
  $('#vkusers').append("<hr>");
  $('#vkusers').append('<div class="notice"><%= @error %></div>');
<% else %>
  $('#vkusers').append("<hr>");
  <% if @vkusers.blank? %>
    $('#vkusers').html("Поздравляем, список обработан полностью!");
  <% else %>
    $('#vkusers').html("");
    <% @vkusers.each do |vkuser|%>
      $('#vkusers').append("                                                                         \
      <a id='<%= vkuser.vkid %>' href='http://vk.com/write<%= vkuser.vkid %>' target='_blank'>       \
        http://vk.com/write<%= vkuser.vkid %>                                                        \
      </a><br>                                                                                       \
      <script>                                                                                       \
        $('#<%= vkuser.vkid %>').click(function(){                                                   \
          $.ajax({                                                                                   \
            type: 'POST',                                                                            \
            url: '/vkuser_sent',                                                                     \
            data: {vkid: <%= vkuser.vkid %>}                                                         \
          });                                                                                        \
          $('#<%= vkuser.vkid %>').attr('class', 'dmp_sent');                                        \
        })                                                                                           \
      </script>");
    <% end %>
  <% end %>
<% end %>